### PR TITLE
fix readme typo

### PR DESCRIPTION
**Pull request by dym-sh**

### CODE REVIEW

**Comment by ECorreia45** [comment]
Are there more typos fix?

**Comment by dym-sh** [comment]
i saw no more typos, but the 

> `🚫 No JSX!`

is confusing:
- is it the positive feature that is amplified by the  `🚫`
- a negative feature
- [ ] the stylization of unchecked checkbox (as in "we still working on removing JSX")
- double-negative ("NO No JSX")

i would just use :+1: for every list item, given they all positive features

**Comment by ECorreia45** [comment]
I like that idea actually. Do you want to improve that section as well? Keep the icon and remove the double negation.

Thanks for that suggestion. Keep them coming

**Comment by dym-sh** [comment]
just change it the next time you gonna edit it, i dont strive for credit :shrug:

**Pull request closed without merging**
